export const SCOPE_APPLICATION_PREFIX = "WFRM.";

export const ROLES_UI = {
    WFRM_SECTION_STAFF: `${SCOPE_APPLICATION_PREFIX}WFRM_SECTION_STAFF`, //tier 1 (create/read/update/delete all access)
    WFRM_WILDFIRE_STAFF: `${SCOPE_APPLICATION_PREFIX}WFRM_WILDFIRE_STAFF`, //tier 2/3 (read-only all, but create/update/delete for self and group members if leader of group)
    WFRM_ADMIN_RESOURCE_VIEWER: `${SCOPE_APPLICATION_PREFIX}WFRM_ADMIN_RESOURCE_VIEWER`, //tier 4 (read-only)
};

export const SCOPES_UI = {
    UPDATE_ANY_WILDFIRE_RESOURCE: `${SCOPE_APPLICATION_PREFIX}UPDATE_ANY_WILDFIRE_RESOURCE`,
    GET_ANY_WILDFIRE_RESOURCE: `${SCOPE_APPLICATION_PREFIX}GET_ANY_WILDFIRE_RESOURCE`,
    GET_WILDFIRE_RESOURCE: `${SCOPE_APPLICATION_PREFIX}GET_WILDFIRE_RESOURCE`,
    CREATE_WILDFIRE_RESOURCE: `${SCOPE_APPLICATION_PREFIX}CREATE_WILDFIRE_RESOURCE`,
    UPDATE_WILDFIRE_RESOURCE: `${SCOPE_APPLICATION_PREFIX}UPDATE_WILDFIRE_RESOURCE`,
    DELETE_WILDFIRE_RESOURCE: `${SCOPE_APPLICATION_PREFIX}DELETE_WILDFIRE_RESOURCE`,

    GET_ANY_GROUP: `${SCOPE_APPLICATION_PREFIX}GET_ANY_GROUP`,
    GET_GROUP: `${SCOPE_APPLICATION_PREFIX}GET_GROUP`,
    CREATE_GROUP: `${SCOPE_APPLICATION_PREFIX}CREATE_GROUP`,
    UPDATE_GROUP: `${SCOPE_APPLICATION_PREFIX}UPDATE_GROUP`,
    DELETE_GROUP: `${SCOPE_APPLICATION_PREFIX}DELETE_GROUP`,

    GET_GROUP_TEMPLATE: `${SCOPE_APPLICATION_PREFIX}GET_GROUP_TEMPLATE`,
    // UPDATE_GROUP_TEMPLATE: `${SCOPE_APPLICATION_PREFIX}UPDATE_GROUP_TEMPLATE`, //don't need these
    // CREATE_GROUP_TEMPLATE: `${SCOPE_APPLICATION_PREFIX}CREATE_GROUP_TEMPLATE`,
    // DELETE_GROUP_TEMPLATE: `${SCOPE_APPLICATION_PREFIX}DELETE_GROUP_TEMPLATE`,

    GET_GROUP_GROUP_MEMBER: `${SCOPE_APPLICATION_PREFIX}GET_GROUP_GROUP_MEMBER`,
    CREATE_GROUP_GROUP_MEMBER: `${SCOPE_APPLICATION_PREFIX}CREATE_GROUP_GROUP_MEMBER`,
    UPDATE_GROUP_GROUP_MEMBER: `${SCOPE_APPLICATION_PREFIX}UPDATE_GROUP_GROUP_MEMBER`,
    DELETE_GROUP_GROUP_MEMBER: `${SCOPE_APPLICATION_PREFIX}DELETE_GROUP_GROUP_MEMBER`,

    GET_PERSON_PERSONAL_CHARACTERISTIC: `${SCOPE_APPLICATION_PREFIX}GET_PERSON_PERSONAL_CHARACTERISTIC`,
    CREATE_PERSON_PERSONAL_CHARACTERISTIC: `${SCOPE_APPLICATION_PREFIX}CREATE_PERSON_PERSONAL_CHARACTERISTIC`,
    UPDATE_PERSON_PERSONAL_CHARACTERISTIC: `${SCOPE_APPLICATION_PREFIX}UPDATE_PERSON_PERSONAL_CHARACTERISTIC`,
    DELETE_PERSON_PERSONAL_CHARACTERISTIC: `${SCOPE_APPLICATION_PREFIX}DELETE_PERSON_PERSONAL_CHARACTERISTIC`,

    GET_RESOURCE_UNIT_CONTACT: `${SCOPE_APPLICATION_PREFIX}GET_RESOURCE_UNIT_CONTACT`,
    CREATE_RESOURCE_UNIT_CONTACT: `${SCOPE_APPLICATION_PREFIX}CREATE_RESOURCE_UNIT_CONTACT`,
    UPDATE_RESOURCE_UNIT_CONTACT: `${SCOPE_APPLICATION_PREFIX}UPDATE_RESOURCE_UNIT_CONTACT`,
    DELETE_RESOURCE_UNIT_CONTACT: `${SCOPE_APPLICATION_PREFIX}DELETE_RESOURCE_UNIT_CONTACT`,

    GET_RESOURCE_UNIT_COMMUNICATION: `${SCOPE_APPLICATION_PREFIX}GET_RESOURCE_UNIT_COMMUNICATION`,
    CREATE_RESOURCE_UNIT_COMMUNICATION: `${SCOPE_APPLICATION_PREFIX}CREATE_RESOURCE_UNIT_COMMUNICATION`,
    UPDATE_RESOURCE_UNIT_COMMUNICATION: `${SCOPE_APPLICATION_PREFIX}UPDATE_RESOURCE_UNIT_COMMUNICATION`,
    DELETE_RESOURCE_UNIT_COMMUNICATION: `${SCOPE_APPLICATION_PREFIX}DELETE_RESOURCE_UNIT_COMMUNICATION`,

    GET_RESOURCE_GROUP_CONTACT: `${SCOPE_APPLICATION_PREFIX}GET_RESOURCE_GROUP_CONTACT`,
    CREATE_RESOURCE_GROUP_CONTACT: `${SCOPE_APPLICATION_PREFIX}CREATE_RESOURCE_GROUP_CONTACT`,
    UPDATE_RESOURCE_GROUP_CONTACT: `${SCOPE_APPLICATION_PREFIX}UPDATE_RESOURCE_GROUP_CONTACT`,
    DELETE_RESOURCE_GROUP_CONTACT: `${SCOPE_APPLICATION_PREFIX}DELETE_RESOURCE_GROUP_CONTACT`,

    GET_RESOURCE_GROUP_COMMUNICATION: `${SCOPE_APPLICATION_PREFIX}GET_RESOURCE_GROUP_COMMUNICATION`,
    CREATE_RESOURCE_GROUP_COMMUNICATION: `${SCOPE_APPLICATION_PREFIX}CREATE_RESOURCE_GROUP_COMMUNICATION`,
    UPDATE_RESOURCE_GROUP_COMMUNICATION: `${SCOPE_APPLICATION_PREFIX}UPDATE_RESOURCE_GROUP_COMMUNICATION`,
    DELETE_RESOURCE_GROUP_COMMUNICATION: `${SCOPE_APPLICATION_PREFIX}DELETE_RESOURCE_GROUP_COMMUNICATION`,


    GET_RESOURCE_UNIT_ADDRESS: `${SCOPE_APPLICATION_PREFIX}GET_RESOURCE_UNIT_ADDRESS`,
    // CREATE_RESOURCE_UNIT_ADDRESS: `${SCOPE_APPLICATION_PREFIX}CREATE_RESOURCE_UNIT_ADDRESS`, //dont need these
    // UPDATE_RESOURCE_UNIT_ADDRESS: `${SCOPE_APPLICATION_PREFIX}UPDATE_RESOURCE_UNIT_ADDRESS`,
    // DELETE_RESOURCE_UNIT_ADDRESS: `${SCOPE_APPLICATION_PREFIX}DELETE_RESOURCE_UNIT_ADDRESS`

    GET_GROUP_AVAILABILITY: `${SCOPE_APPLICATION_PREFIX}GET_GROUP_AVAILABILITY`,
    UPDATE_GROUP_AVAILABILITY: `${SCOPE_APPLICATION_PREFIX}UPDATE_GROUP_AVAILABILITY`,

    GET_WILDFIRE_RESOURCE_AVAILABILITY: `${SCOPE_APPLICATION_PREFIX}GET_WILDFIRE_RESOURCE_AVAILABILITY`,
    UPDATE_WILDFIRE_RESOURCE_AVAILABILITY: `${SCOPE_APPLICATION_PREFIX}UPDATE_WILDFIRE_RESOURCE_AVAILABILITY`,

    GET_ASSIGNMENT: `${SCOPE_APPLICATION_PREFIX}GET_ASSIGNMENT`,
    CREATE_ASSIGNMENT: `${SCOPE_APPLICATION_PREFIX}CREATE_ASSIGNMENT`,
    UPDATE_ASSIGNMENT: `${SCOPE_APPLICATION_PREFIX}UPDATE_ASSIGNMENT`,

    GET_ASSIGNMENT_MEMBER: `${SCOPE_APPLICATION_PREFIX}GET_ASSIGNMENT_MEMBER`,
    CREATE_ASSIGNMENT_MEMBER: `${SCOPE_APPLICATION_PREFIX}CREATE_ASSIGNMENT_MEMBER`,
    UPDATE_ASSIGNMENT_MEMBER: `${SCOPE_APPLICATION_PREFIX}UPDATE_ASSIGNMENT_MEMBER`,
    DELETE_ASSIGNMENT_MEMBER: `${SCOPE_APPLICATION_PREFIX}DELETE_ASSIGNMENT_MEMBER`,

    GET_RESOURCE_CLASSIFICATION: `${SCOPE_APPLICATION_PREFIX}GET_RESOURCE_CLASSIFICATION`,

};
